@startuml

skinparam linetype ortho

component "CLI"
component "Setup Service"

package "Bases de Datos" {

  package "MySQL" {
    rectangle Cliente
    rectangle Sucursal
    rectangle Promocion
    rectangle Producto
    rectangle Tipo_Producto
    rectangle Stock
  }

  package "MongoDB" {
    rectangle Ticket
    rectangle Interaccion
    rectangle Canje
    rectangle MenuDiaCache
  }

  package "Redis" {
    rectangle RedisCache
  }

  package "Cassandra" {
    rectangle HistorialCompra
  }

  package "Neo4j" {
    rectangle Neo4jCliente
  }
}

' Relaciones
CLI --> Cliente
CLI --> Ticket
CLI --> HistorialCompra
CLI --> Neo4jCliente
CLI --> RedisCache

Setup --> Cliente
Setup --> Ticket
Setup --> HistorialCompra
Setup --> Neo4jCliente
Setup --> RedisCache

Cliente "1" -- "N" Ticket
Neo4jCliente "N" -- "N" Neo4jCliente : SIGUE

@enduml