# .devcontainer/docker-compose.yml
# version: '3.8'

services:
  cat_track:
    environment:
      # MySQL
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root_password # Usamos la variable de ambiente
      - MYSQL_DB=cat_track_profiles
      # MongoDB
      - MONGO_URI=mongodb://mongodb:27017/
      # Cassandra
      - CASSANDRA_HOSTS=cassandra
      - CASSANDRA_PORT=9042
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8888:8888"

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_data_warehouse
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ..:/workspace:cached
  
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    # Variables de entorno opcionales para configuración
    environment:
      - CASSANDRA_START_RPC=true
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra
  neo4j:
      image: neo4j:latest
      container_name: neo4j-server
      ports:
        # Puerto HTTP para la interfaz web (Neo4j Browser)
        - "7474:7474"
        # Puerto Bolt para la conexión de drivers y aplicaciones
        - "7687:7687"
      volumes:
        - neo4j_data:/var/lib/neo4j
        # (Opcional) Monta un volumen para logs
        # - neo4j_logs:/logs
        # (Opcional) Monta un volumen para la configuración
        # - neo4j_conf:/var/lib/neo4j/conf
      environment:
        # IMPORTANTE: Establece la contraseña inicial para el usuario 'neo4j'
        - NEO4J_AUTH=neo4j/neo4jpassword
        # (Opcional) Permite conexiones sin autenticación
        # - NEO4J_AUTH=NONE
      # restart: unless-stopped

volumes:
  mysql_data:
  mongodb_data:
  cassandra_data:
  neo4j_data: