# .devcontainer/docker-compose.yml
# version: '3.8'

services:
  cat_track:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    ports:
      - "8888:8888"
    command: sleep infinity

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_data_warehouse
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
      - ..:/workspace:cached
  
  cassandra:
    image: cassandra:latest
    container_name: cassandra
    # Variables de entorno opcionales para configuración
    environment:
      - CASSANDRA_START_RPC=true
    ports:
      - "9042:9042"
    volumes:
      - cassandra_data:/var/lib/cassandra

volumes:
  mysql_data:
  mongodb_data:
  cassandra_data: