# .devcontainer/docker-compose.yml
# version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspace:cached
    # Mapea el puerto de Jupyter Notebook
    ports:
      - "8888:8888"
    command: sleep infinity

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: my_data_warehouse
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  # Nuevo servicio para MongoDB
  mongodb:
    image: mongo:latest
    # Variables de entorno para MongoDB
    environment:
      # No es necesario establecer un usuario y contraseña para un entorno de desarrollo simple.
      # Para producción, es muy recomendable.
      MONGO_INITDB_ROOT_USERNAME: rootuser
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    # Mapea el puerto por defecto de MongoDB (27017)
    ports:
      - "27017:27017"
    # Monta un volumen para que los datos persistan
    volumes:
      - mongodb_data:/data/db
      - ..:/workspace:cached

volumes:
  mysql_data:
  mongodb_data: